### ISSUE TITLE
Student Tracker API

### ISSUE THREAD

**Issue by joeljuca** [sulfurshade/student-app#11]
The Student Tracker API allows an authenticated user to manage data of his/her account through HTTP requests.

## REST collections

**User**

```
- /users
  - GET: [ {User} ]
  - POST: new {User}
- /users/:_id
  - GET: shows {User}
  - PUT: updates {User}
  - DELETE: destroys {User}
```

**Student**

```
- /students
  - GET: [ {Student} ]
  - POST: new {Student}
- /users/:_id
  - GET: shows {Student}
  - PUT: updates {Student}
  - DELETE: destroys {Student}
```

**SessionLog**

```
- /session-logs
  - GET: [ {SessionLog} ]
  - POST: new {SessionLog}
- /users/:_id
  - GET: shows {SessionLog}
  - PUT: updates {SessionLog}
  - DELETE: destroys {SessionLog}
```

## Tasks

- [ ] Implement the User endpoint
  - [ ] User model
  - [ ] User route
  - [ ] Functional tests
- [ ] Implement the Student endpoint
  - [ ] Student model
  - [ ] Student route
  - [ ] Functional tests
- [ ] Implement the SessionLog endpoint
  - [ ] SessionLog model
  - [ ] SessionLog route
  - [ ] Functional tests
